server:
  port: 8080
spring:
  application:
    name: account
  profiles:
    active: k8s, prod
  config:
    import: configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true